resturants/urls.py
from django.urls import path
from resturants.views import (
    ResturantListView,
    ResturantDetailView,
    ResturantCreateView,
)
app_name= "resturants"
urlpatterns = [
    path('', ResturantListView.as_view(), name="list"),
    path('create/', ResturantCreateView.as_view(), name="create"),
    path('<str:slug>/', ResturantDetailView.as_view(), name="detail"),
]

trydjango2/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.urls import include

from resturants.views import (
    ResturantListView,
    ResturantDetailView,
    ResturantCreateView,
)
from userauth.views import SignUpView, UserProfileView, UserLoginView, UserProfileUpdateView

# urlpatterns = [
#     path('admin/', admin.site.urls),
#
#     path('login/', UserLoginView.as_view()),
#     path('logout/', LogoutView.as_view(next_page="/login/")),
#     path('signup/', SignUpView.as_view()),
#     path('user-profile/', UserProfileView.as_view()),
#     path('user-profile/update/', UserProfileUpdateView.as_view()),
#
#     path('resturants/', ResturantListView.as_view()),
#     path('resturants/create/', ResturantCreateView.as_view()),
#     path('resturants/<str:slug>/', ResturantDetailView.as_view()),
#
#     path('home/', TemplateView.as_view(template_name="hello.html")),
#     path('about/', TemplateView.as_view(template_name="about.html")),
#
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("userauth.urls", namespace="userauth")),
    path('resturants/', include("resturants.urls", namespace="resturants")),
    path('home/', TemplateView.as_view(template_name="hello.html"), name="home"),
    path('about/', TemplateView.as_view(template_name="about.html"), name="about"),


]

userauth/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from userauth.views import SignUpView, UserProfileView, UserLoginView, UserProfileUpdateView
app_name= "userauth"
urlpatterns = [
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="/login/"), name="logout"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('user-profile/', UserProfileView.as_view(), name="profile"),
    path('user-profile/update/', UserProfileUpdateView.as_view(), name="update"),

]

resturants/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from .validators import validate_resturant_category, validate_resturant_name
from userauth.models import CustomUser


# Create your models here.
class ResturantLocation(models.Model):
    name = models.CharField(max_length=120, validators=[validate_resturant_name])
    location = models.CharField(max_length=120, null=True, blank=True)

    category = models.CharField(max_length=120, null=True, blank=True, validators=[validate_resturant_category])
    owner = models.ForeignKey(CustomUser, blank=True, null=True, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, blank=True)


    def __str__(self):
        return self.name


def pre_save_receiver(sender, instance, *args, **kwargs):
    print("saving {}".format(instance))
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
    instance.category = instance.category.capitalize()


def post_save_receiver(sender, instance, created, *args, **kwargs):
    print("saved {}".format(created))


pre_save.connect(pre_save_receiver, sender=ResturantLocation)

post_save.connect(post_save_receiver, sender=ResturantLocation)

userauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class CustomUser(AbstractUser):
    location = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.username

resturants/forms.py
from django import forms
from .models import ResturantLocation


class ResturantCreateForm(forms.Form):
    name = forms.CharField(max_length=120)
    location = forms.CharField(max_length=120, required=False)
    category = forms.CharField(max_length=120, required=False)


class ResturantLocationModelForm(forms.ModelForm):
    class Meta:
        model = ResturantLocation
        fields = [
            "name",
            "location",
            "category"
        ]

userauth/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "first_name", "last_name", "email", "location"]


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = "__all__"


class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "email", "location"]

resturants/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import HttpResponseRedirect, Http404
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import ResturantLocation
from .forms import ResturantCreateForm, ResturantLocationModelForm


# Create your views here.
class ResturantListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy("userauth:login")
    template_name = "resturants/resturant_list.html"

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            queryset = ResturantLocation.objects.filter(owner__username__exact=user)
        else:
            raise Http404
        return queryset


class ResturantDetailView(DetailView):
    def get_object(self, queryset=None):
        slug = self.kwargs.get("slug")
        obj = get_object_or_404(ResturantLocation, slug=slug)
        return obj


class ResturantCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("userauth:login")
    form_class = ResturantLocationModelForm
    template_name = "resturants/form.html"
    success_url = reverse_lazy("resturants:list")

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner =self.request.user
        return super().form_valid(form)

userauth/views.py
# users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView
from django.views.generic import DetailView, UpdateView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm, CustomUserUpdateForm
from .models import CustomUser

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'userauth/signup.html'
    def get_success_url(self):
        return reverse_lazy("userauth:login")


class UserLoginView(LoginView):
    template_name = 'userauth/login.html'
    redirect_authenticated_user=True
    def get_success_url(self):
        return reverse_lazy("userauth:profile")


class UserProfileView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy("userauth:login")
    template_name = "userauth/profile.html"

    def get_object(self, queryset=None):
        username = self.request.user.get_username()
        user_detail = get_object_or_404(CustomUser, username=username)
        return user_detail

class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("userauth:login")
    form_class = CustomUserUpdateForm
    template_name = "userauth/update.html"

    def get_object(self, queryset=None):
        username = self.request.user.get_username()
        user_detail = get_object_or_404(CustomUser, username=username)
        return user_detail

    def get_success_url(self):
        return reverse_lazy("userauth:profile")

resturants/templates/resturants/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Add Resturant</h1>
    <form method='POST'>

        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Save</button>



    </form>
{% endblock %}

resturants/templates/resturants/resturant_list.html
{% extends "base.html" %}
{% block content %}
    <h2>Resturant's</h2>
    {% for resturant in object_list %}
{#        <li><a href="/resturants/{{ resturant.slug }}">{{ resturant.name }}</a></li>#}
        <li><a href="{% url 'resturants:detail' slug=resturant.slug %}">{{ resturant.name }}</a></li>
    {% endfor %}
{% endblock %}

resturants/templates/resturants/resturantlocation_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ resturantlocation.name }}<small> {{ resturantlocation.category }}</small></h1>
    <p>{{ resturantlocation.location }}</p>
    <p><i>Added to database on:</i> {{ resturantlocation.timestamp|date }} || <i>Updated:</i> {{ resturantlocation.updated|timesince }} ago</p>
{% endblock %}

templates/about.html
{% extends "base.html" %}


{% block content %}
{#{{ block.super }}#}
<h1>ABOUT US</h1><br>
    <p><h4>We are learning the django framework fundamentals</h4></p>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include "snippets/css.html" %}

    <title>Hello, world!</title>
</head>
<body>

<div class="container">
    {% include "snippets/nav.html" %}

    {% block content %}
        This is from base.html content block
    {% endblock %}

    {% block content2 %}
        This is from base.html content2 block. It need to be replaced.
    {% endblock %}

</div>


{% include "snippets/js.html" %}
</body>
</html>

templates/hello.html
{% extends "base.html" %}


{% block content %}
{#{{ block.super }}#}

<h1>Hello, world!</h1><br>

{% endblock %}

templates/snippets/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

templates/snippets/js.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

templates/snippets/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'resturants:list' %}">Resturant</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="#">TryDjango2</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userauth:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
</nav>

templates/welcome.html
{% extends "base.html" %}


{% block content %}

<h2>Welome to the resturants page</h2>
Resturant name is {{ resturant_name }}<br>

{% if items %}
    The items are <br>
    {% for item in items %}
        <li>{{ item }}</li>
    {% endfor %}
{% endif %}

{% endblock %}

userauth/templates/userauth/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container row col-6 offset-md-4 align-items-center">
        {% if not user.is_authenticated %}

            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit">Login</button>
            </form>
        {% else %}
            <br>You are already logged in.<br>
        {% endif %}
    </div>

{% endblock %}
{% block content2 %}

{% endblock %}

userauth/templates/userauth/profile.html
{% extends 'base.html' %}

{% block content %}
    <h3>Fullname: {{ object.first_name }} {{ object.last_name}}</h3>
    <p>Username: {{ object.username }}</p>
    <p>Location: {{ object.location }}</p>
    <p>Email: {{ object.email }}</p>
{% endblock %}

userauth/templates/userauth/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if not user.is_authenticated %}
        <h2>Sign up</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Sign up</button>
        </form>
    {% endif %}
{% endblock %}

userauth/templates/userauth/update.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Update</button>
    </form>
{% endblock %}